### ISSUE TITLE
Ошибка обработки сообщений

### ISSUE THREAD

**Issue by Slavenin** [nixys/nxs-chat-srv#1]
Здравствуйте!
При добавлении бота в логе выводится такая информация:
> [29.01.2018 08:19:52.307353]	(829)	DEBUG:		[rest-api]: received message from telegram (auth token: "xxx" (correct), post body: "{"update_id":xxxx,
> "message":{"message_id":28,"from":{"id":xxx,"is_bot":false,"first_name":"xxx","last_name":"xxx","username":"xxx","language_code":"ru-RU"},"chat":{"id":xxxx,"first_name":"xxxx","username":"xxxx","type":"private"},"date":1517213995,"text":"/start","entities":[{"offset":0,"length":6,"type":"bot_command"}]}}
> [29.01.2018 08:19:52.307547]	(829)	DEBUG:		[rest-api]: ra queue add: success
> [29.01.2018 08:19:52.307586]	(829)	INFO:		connection accepted	149.154.167.208:60452	"POST /tlgrm?token=xxxx"	200	52	""
> [29.01.2018 08:19:52.380276]	(823)	DEBUG:		[queue-worker]: ra queue get: success
> [29.01.2018 08:19:52.380983]	(823)	DEBUG:		[queue-worker]: db cache get: success (cache type: projects)
> [29.01.2018 08:19:52.381440]	(823)	DEBUG:		[queue-worker]: db cache get: success (cache type: users)
> [29.01.2018 08:19:52.382512]	(823)	DEBUG:		[queue-worker]: db cache get: success (cache type: issue_priorities)
> [29.01.2018 08:19:52.385497]	(823)	DEBUG:		[queue-worker]: db queue add: success (tlgrm userid: xxxx)
> [29.01.2018 08:19:52.600177]	(825)	DEBUG:		[queue-worker]: db queue set lock: key is already locked by another process (tlgrm user id: xxxx)
> [29.01.2018 08:19:52.600236]	(824)	DEBUG:		[queue-worker]: db queue set lock: success (tlgrm user id: xxxx, lock expire ms: 30000)
> [29.01.2018 08:19:52.600269]	(827)	DEBUG:		[queue-worker]: db queue set lock: key is already locked by another process (tlgrm user id: xxxxx)
> [29.01.2018 08:19:52.600467]	(824)	DEBUG:		[queue-worker]: db queue get: success (tlgrm user id: xxxx)
> [29.01.2018 08:19:52.600489]	(826)	DEBUG:		[queue-worker]: db queue set lock: key is already locked by another process (tlgrm user id: xxxx)
> [29.01.2018 08:19:52.600690]	(824)	DEBUG:		[queue-worker]: db queue get: success (tlgrm user id: xxxx)
> [29.01.2018 08:19:52.600897]	(824)	DEBUG:		[queue-worker]: db cache get: success (cache type: projects)
> [29.01.2018 08:19:52.601347]	(824)	DEBUG:		[queue-worker]: db cache get: success (cache type: users)
> [29.01.2018 08:19:52.602610]	(824)	DEBUG:		[queue-worker]: db cache get: success (cache type: issue_priorities)
> [29.01.2018 08:19:52.602779]	(824)	DEBUG:		[queue-worker]: db session get: value does not exist (tlgrm userid: xxxx)
> [29.01.2018 08:19:52.801667]	(824)	WARNING:	[queue-worker]: tlgrm request error: wrong Telegram response code (response code: 404, response body: "")
> [29.01.2018 08:19:52.801699]	(824)	ERROR:		[queue-worker]: can't send tlgrm message (message: "{"chat_id":xxxx,"parse_mode":"","disable_web_page_preview":false,"text":"Максим, добро пожаловать в чат поддержки Nixys!\nС нетерпением ждём Ваших задач :)"}")
> [29.01.2018 08:19:52.801705]	(824)	WARNING:	[queue-worker]: error in 'proc.queue-worker.tlgrm-update.handler_message_exec' (user id: xxxx, error code: 2)
> [29.01.2018 08:20:02.879675]	(828)	DEBUG:		[cache-worker]: rdmn enums issue priorities get: success
> [29.01.2018 08:20:02.879920]	(828)	DEBUG:		[cache-worker]: db cache put: success (cache type: issue_priorities)
> [29.01.2018 08:20:02.879949]	(828)	DEBUG:		[cache-worker]: issue priorities cache successfully updated

**Comment by borisershov** [comment]
Здравствуйте!

Скажите, пожалуйста, какая версия бота у Вас установлена (`nxs-chat-srv -v`)?

И ещё: не начинается ли в конфиге значение ключа `telegram.bot_api_key` с префикса `bot`?

**Comment by Slavenin** [comment]
```bash
root@93071:~# nxs-chat-srv -v
nxs-chat-srv: version: 0.1.14 (nxs-fw v1.12.0)
```
нет, не начинается.
![image](https://user-images.githubusercontent.com/4180077/35509789-a1e3c5ec-0506-11e8-94d4-d0a03070bbbe.png)

**Comment by borisershov** [comment]
Проблема заключалась в том, что после обновления пакета и выполнения команды `service nxs-chat-srv stop` для остановки сервиса `nxs-chat-bot` процесс не получил сигнал SIGTERM и, как следствие, продолжила работать старая версия ПО.
Повторное выполнение `service nxs-chat-srv stop` сработало корректно.

На текущий момент не удалось установить причины такого поведения. Также, за всё время такая проблема встречается впервые.
Этот момент будет ещё дополнительно изучен и в случае необходимости - исправлен код бота.

Полагаю, что данную задачу можно закрывать, т.к. основной вопрос решён.
