### ISSUE TITLE
Сертификат

### ISSUE THREAD

**Issue by siugaron** [nixys/nxs-chat-srv#13]
Ещё раз добрый день)
А не подскажете, какой конфиг отвечает за обработку сертификатов.
Дело в том, что у меня Let's Encrypt и телеграм в упор не хочет его верифицировать. Ни как самоподписанный ни как нормальный.
SSL верификатор по порту, подсказал мне что делать. На 443 порту я настроил и получил от верификатора оценку A. Однако на 8443 где бы я ни настраивал, получаю оценку C+

**Comment by siugaron** [comment]
{
    "ok": true,
    "result": {
        "url": "https://support.acomps.ru:8443/tlgrm?token=token",
        "has_custom_certificate": false,
        "pending_update_count": 22,
        "last_error_date": 1526311735,
        "last_error_message": "SSL error {337047686, error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed}",
        "max_connections": 40
    }
}

Вот лог из самого телеграма

Сейчас попробую сменить cert.pem на fullchain.pem
Может поможет.

**Comment by borisershov** [comment]
Отлично! Надеюсь, наше приложение будет полезным для вашей компании :)

Задачу тогда закрываю.
