### ISSUE TITLE
Postgres support

### ISSUE THREAD

**Issue by therequest** [nixys/nxs-chat-srv#16]
Hi,
is there a way to get postgres as database instead of mysql?

**Comment by borisershov** [comment]
Hello!

No, unfortunately, PSQL not supported by nsx-chat-srv.

P.S. Sorry for the late reply (

**Comment by KES777** [comment]
What is required to implement support for PG?

Does this plugin works if redmine is configured to work with postgres?

**Comment by AndreiMuvila** [comment]
Hello! 

> What is required to implement support for PG?

There are no plans to implement PostgreSQL support at this time. 

> Does this plugin works if redmine is configured to work with postgres?

The bot's server side works with MySQL. Since the Docker container is used here, MySQL for the bot can be deployed in a container. Plugin in Redmine with PostgreSQL working correctly.
