### ISSUE TITLE
Telegram bot not receiving messages

### ISSUE THREAD

**Issue by joseluiscampos** [nixys/nxs-chat-srv#17]
Hi, 

I was trying to get the nxs-chat-srv working but Im facing problems to get the Telegram bot receive messages.

Im running the nxs-chat-srv with docker and already modified and tested all the config required in docker compose. Im using Letsencrypt and in my domain I see that the certificate is valid issued by Letsencrypt, I already configured the webhook in redmine (owned by my company and also configured with Letsencrypt) and Im receiving this kind of messages in nxs-chat-srv when I create and update issues in redmine:

`[rest-api]: received message from telegram (auth token: "j1KiIqmZJ30QRhtgUGjW" (correct), post body: "{"action":"issue_edit","data":{"issue":{"id":7738,"project":{"id":277,"name":"DIA SETAI","members":[{"id":4,"name":"Roberto A. Baños Alvarez","access":{"view_current_issue":true,"view_private_notes":true}................`

and when I /start the bot in telegram I saw: 

```
[rest-api]: received message from telegram (auth token: "j1KiIqmZJ30QRhtgUGjW" (correct), post body: "{"update_id":757098575,
nxs-chat-srv_1  | "message":{"message_id":90,"from":{"id":821370166,"is_bot":false,"first_name":"Jos\u00e9","last_name":"Campos"," ..............

```
Im not able to see any message in my Telegram bot when issues are created or updated, also I dont know how to set commands in my bot, I was digging in source code an I saw something like /ext but I dont know how to use it.

I send /ext hello world and I saw in logs:

```
nxs-chat-srv_1  | [15.05.2019 05:23:13.741393]  (169)   DEBUG:          [rest-api]: received message from telegram (auth token: "j1KiIqmZJ30QRhtgUGjW" (correct), post body: "{"update_id":757098576,
nxs-chat-srv_1  | "message":{"message_id":92,"from":{"id":821370166,"is_bot":false,"first_name":"Jos\u00e9","last_name":"Campos","username":"joseluiscampos","language_code":"es"},"chat":{"id":821370166,"first_name":.........
```

Its important to mention that I saw constantly this warning in logs and dont know if it could be the problem: 

```
nxs-chat-srv_1  | [15.05.2019 05:23:43.900951]  (168)   DEBUG:          [cache-worker]: rdmn users get: success (user id: 0, offset: 0, limit: 100)
nxs-chat-srv_1  | [15.05.2019 05:23:43.901465]  (168)   WARNING:        [cache-worker]: users cache update error

```

What other commands exists, and what could be the problem in my config or bot that cause that no message were received in Telegram Desktop?

Any help will be highly appreciated.

The redmine server is running here: https://proyectos.pragmati.com.mx  and the nxs-chat-srv in https://nxs-chat.pragmati.com.mx

Best regards

**Comment by borisershov** [comment]
Hi!

It's possible to see more logs? Ideally, if you will clear the nxs-chat-srv logs, then update certain Redmine issue and show me whole the logs. Also, it would be more valuable if you can show the config (in this case, please, hide all sensitive data).

If you wish, you may write [me](https://t.me/borisershov) in a Telegram and provide all requested data.

**Comment by AndreiMuvila** [comment]
Hello.

There were no new questions on the problem for a long time. We close it.
