### ISSUE TITLE
Возможность изменения приветственного сообщения

### ISSUE THREAD

**Issue by Slavenin** [nixys/nxs-chat-srv#2]
Здравствуйте! Сейчас приветственное сообщение захардкожено в константе https://github.com/nixys/nxs-chat-srv/blob/e8c1152a11d118af4d61520b4293aa0497e695ed/src/nxs-chat-srv-core.h  Хотелось бы иметь возможность его изменения, так как наша компания называется совсем не Nixys....

**Comment by borisershov** [comment]
Здравствуйте!

Мы сейчас как раз работаем над тем, чтобы была возможность изменять все сообщения бота.
Ожидаем завершить это улучшение в ближайшие 1-2 дня. По итогам я дополнительно дам знать в этой задаче.

**Comment by borisershov** [comment]
Здравствуйте!

Требуемый Вам функционал по изменению приветственного сообщения, а так же некоторые другие улучшения, доступны в версии [v0.2.0](https://github.com/nixys/nxs-chat-srv/releases/tag/v0.2.0). Обращаю особое внимание на необходимость обновления плагина для Redmine до версии [v2.0](https://github.com/nixys/nxs-chat-redmine/releases/tag/v2.0).

Прошу ознакомиться с релизом и сообщить если у Вас возникнут какие-либо вопросы.

**Comment by Maxonz** [comment]
Добрый день.

Подскажите где настраивается приветственное сообщение? в .conf файле? в ридми не нашел

**Comment by borisershov** [comment]
Здравствуйте!

Возможность менять приветственное сообщение появилась в версии nxs-chat-srv 0.2.0.

Если у Вас уже установлена более ранняя версия, то её необходимо обновить до последней.
После этого нужно добавить следующий дополнительный блок настроек ([ссылка на конфигурационный файл в новой версии](https://raw.githubusercontent.com/nixys/nxs-chat-srv/master/build-pkgs-conf/pkg/general/etc/nxs-chat-srv/nxs-chat-srv.conf)) в конфигурационный файл:

```
	"labels": {
		"default_lang": "en",
		"labels_path": "/usr/share/nxs-chat-srv/labels/"
	},
	"greetings": [
		{
			"lang": "ru",
			"text": "%{userfname}, добро пожаловать в чат поддержки клиентов нашей компании!\nС нетерпением ждём Ваших задач."
		},
		{
			"lang": "en",
			"text": "%{userfname}, welcome to our customer care system chat!\nWe are looking forward to your issues."
		}
	]
```

Так же привожу ссылки на описание новых опций в конфигурационном файле:
- Блок [labels](https://github.com/nixys/nxs-chat-srv#labels)
- Блок [greetings](https://github.com/nixys/nxs-chat-srv#greetings)

**Comment by Maxonz** [comment]
Спасибо за ответ, в conf добавил, теперь его перезапустить как-то надо что бы настройки новые подтянул?
