### ISSUE TITLE
Вопрос про функционал: анонимное создание задач

### ISSUE THREAD

**Issue by mrPsycho** [nixys/nxs-chat-srv#30]
здравствуйте,

хочу уточнить - есть ли возможность создавать задачи в редмайне от анонимов? Например, добавив в whitelist разрешенный домен.

те, история такая:
есть редмайн. 
Перед тем как тикет создать, пользователь должен войти в этот самый редмайн, чтобы его аккаунт создался.
Но многим он не нужен, и они просто хотят ставить задачи. 

Следовательно и вопрос: Если пользователь в боте говорит что его мейл username@good.domain - то бот это хранит у себя (мб в отдельной таблице в редмайне) и при создании тикетов добавляет: "создано юзером username@good.domain"

или такого нет?

**Comment by AndreiMuvila** [comment]
Здравствуйте.
> хочу уточнить - есть ли возможность создавать задачи в редмайне от анонимов? 

Данный функционал реализован. 
Для создания анонимных задач необходимо задать проект и пользователя Presale. Тогда незарегистрированные в Redmine пользователи, смогут создавать задачи в этом проекте через бота от имени presale-пользователя. При создании задачи таким образом, в названии задачи будет указан Telegram ID поставившего задачу пользователя

**Comment by AndreiMuvila** [comment]
Так как дальнейших вопросов не поступал, задачу закрываю.
