### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by Rammzai** [nixys/nxs-chat-srv#36]
Доброго времени суток всем. Пишу вам с просьбой помочь. Кто сталкивался с проблемой обратной связи то есть в боте мы видим назначенные нам проекты  а также можем создавать задачи но вот обратного ответа при изменениях в задаче не получает создатель заявки и назначенный на эту заявку. Уже пробовал выдавать полные права всем но ничего не меняется в логах то же никаких изменений да же ошибки не вылазит что сделано не так ? За ранее спасибо.

**Comment by miniREACTOR** [comment]
У меня та же проблема.
