### ISSUE TITLE
Привязка к userid, а не username. Сборка бинарника.

### ISSUE THREAD

**Issue by gruz123** [nixys/nxs-chat-srv#38]
Скажите пожалуйста, а его можно использовать по userid ? Ники могут менятья, и они не всегда актуальны. 
Еще очень бы хотелось знать как его можно пересобрать? не волоку в C, но может бы пробовал с ребятами или с вашей подсказкой подкинуть перекомпиленный бинарник пока не добьюсь нужного результата. Спасибо!
Поставил gcc,make получаю: 
```
gruz@docker:~/nxs-chat-srv$ sudo make
cc -c -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -I /usr/include/nxs-fw-libs/1.14 -I ./src -I/usr/include/libevent-nxs    -D USE_NXS_JSON -D USE_NXS_CURL -D USE_NXS_MYSQL -D USE_NXS_REST_API  -o objs/nxs-chat-srv-core.o ./src/nxs-chat-srv-core.c
./src/nxs-chat-srv-core.c:1:10: fatal error: nxs-core/nxs-core.h: No such file or directory
    1 | #include <nxs-core/nxs-core.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:24: core] Error 1


```

**Comment by AndreiMuvila** [comment]
Доброго времени суток. 

> Скажите пожалуйста, а его можно использовать по userid ?

Явно его использовать нельзя, бот сам получает userid по username.
Условному менеджеру или бухгалтеру проще вписать свой ник в настройках в систему задач. Все же, свой username знает, как правило, любой пользователь, а userid требует обращения к сторонним инструментам для его получения.

> Еще очень бы хотелось знать как его можно пересобрать?

Вам не хватает библиотек из репозитория https://github.com/nixys/nxs-fw-libs. Там есть описание установки.

Лучше собирать через докер. Но если хочется вручную, то описание шагов сборки есть тут: https://github.com/nixys/nxs-chat-srv/blob/master/deploy/docker/app/Dockerfile

ЗЫ: скоро бот будет переписан на Go. Библиотека уже вышла: https://github.com/nixys/nxs-go-telegram

**Comment by AndreiMuvila** [comment]
> Доброго!) Спасибо за информацию, отлично )

Рад был помочь. Нужно ли что то еще или можно закрыть?

**Comment by gruz123** [comment]
> > Доброго!) Спасибо за информацию, отлично )
> 
> Рад был помочь. Нужно ли что то еще или можно закрыть? 

Нет, это все. Большое спасибо, колупаемся дальше )
