### ISSUE TITLE
Новые telegram id

### ISSUE THREAD

**Issue by gruz123** [nixys/nxs-chat-srv#39]
Добрый день ! Прилетел новый  id  длиннее чем обычно.
Теперь получаю ошибку 
`[07.04.2022 11:07:54.615739]	(167)	ERROR:		[queue-worker]: db ids put tlgrm error, MySQL insert error: Out of range value for column 'tlgrm_userid' at row 1 (tlgrm userid: 5134861499, tlgrm username: chemodan, rdmn userid: 31)

[07.04.2022 11:07:54.615798]	(167)	ERROR:		[queue-worker]: can't save tlgrm ids into DB: put tlgrm error (tlgrm userid: 5134861499, tlgrm username: chemodan, rdmn userid: 31)`
Спасибо.

**Comment by AndreiMuvila** [comment]
Здравствуйте. 

Проблема связана с функциями обработки данных внутри приложения. К сожалению сейчас разработчика на С у нас нет, но мы перерабатываем приложение под Go. В новой версии этот баг будет исправлен.

**Comment by gruz123** [comment]
> Здравствуйте.
> 
> Проблема связана с функциями обработки данных внутри приложения. К сожалению сейчас разработчика на С у нас нет, но мы перерабатываем приложение под Go. В новой версии этот баг будет исправлен.

Понял, Большое спасибо за информацию!
