### ISSUE TITLE
Сборка для Centos

### ISSUE THREAD

**Issue by makarich** [nixys/nxs-chat-srv#4]
Подскажите, ждать?
Пробовал из src, но зависимостей.... :(

**Comment by borisershov** [comment]
Здравствуйте!

Да, в ближайшие 1-2 недели мы планируем выложить сборку для CentOS. Поскольку такой вопрос возник, то я отпишусь об это дополнительно в данной задаче.

Пока Вы можете попробовать развернуть бота через Docker-контейнер. Привожу ссылку на соответствующий раздел в документации: https://github.com/nixys/nxs-chat-srv#dockerfile

**Comment by makarich** [comment]
Если в течении двух недель, то можно и подождать. Спасибо за ответ

**Comment by denchru** [comment]
присоединяюсь, ждем сборку под CentOS)

**Comment by borisershov** [comment]
Добрый день!

Работы по созданию сборки под CentOS мы планируем завершить либо в конце этой недели, либо в начале следующей.

**Comment by denchru** [comment]
Здравствуйте!

Как успехи?)

**Comment by borisershov** [comment]
Здравствуйте!

У нас возникло непредвиденное обстоятельство, которое не позволило завершить работы в ожидаемое время.
Сейчас уже данная задача находится на завершающей стадии, по этому в ближайшее время мы сможем порадовать вас сборкой нашего бота под CentOS. Об этом я ещё дополнительно отпишусь в этой задаче.

**Comment by borisershov** [comment]
Всем привет!

Наконец-то мы добавили поддержку CentOS 7. В этот процесс нам пришлось погрузиться значительно больше, чем мы того ожидали, поэтому получилось так долго. Но зато наши старания могут превратиться в не плохую статью для Хабра :)
В общем, [тут](https://github.com/nixys/nxs-chat-srv#centos) описана инструкция по установке бота в CentOS 7, можете пробовать.

Небольшое замечание: т.к. для CentOS бот протестирован не так тщательно и продолжительно, как для Debian, то прошу сообщить если будут выявлены какие-либо недочёты (включая недочёты в формировании rpm-пакета). Хотя это и Debian'а тоже касается :))

**Comment by borisershov** [comment]
Приветствую!

Полагаю, что данный тикет уже можно закрыть :)
