### ISSUE TITLE
Проблема с новыми telegram id, ожидание новой версии

### ISSUE THREAD

**Issue by openncomp** [nixys/nxs-chat-srv#41]
Здравствуйте, спасибо за вашего бота, очень удобная штука!
Но все чаще прилетают новые длинные telegram id как описано в этом тикете #39 .
Вы там упомянули, что будете переписывать под GO новую версию.

Очень интересно, стоит ли ожидать и хоть примерно когда планируется новая версия?

**Comment by borisershov** [comment]
Здравствуйте! Да, совершенно верно. Недавно мы запустили работы по написанию новой версии бота. В первую очередь будет реализован функционал текущей версии (с исправлением явных багов типа длинных ID пользователей). Это мы планируем завершить в течение ближайших двух месяцев.

**Comment by openncomp** [comment]
Это отличная новость, я действительно рад, что вы не отказались от поддержки этого проекта.
Я даже думать не хотел, что придется подыскивать новый таск трекер взамен редмайну, если вы закроете поддержку этого бота. Он единственный, который хорошо реализует интеграцию Redmine и Telegram.
Да, возможно Redmine не такой популярный продукт в широких массах, но в некоторых узких кругах он до сих пор пользуется популярностью и не хотелось бы начинать заново с другим продуктом.
С нетерпение будем ждать возможности потестить обновленного бота, удачи вам и процветания!

**Comment by openncomp** [comment]
Здравствуйте.
Не хотелось надоедать, но интерес пересилил.
У вас появилась возможность заняться этим проектом?
