### ISSUE TITLE
Сортировка проектов

### ISSUE THREAD

**Issue by titkovdmitry** [nixys/nxs-chat-srv#42]
Добрый день
Когда проектов много, сложно по ним делать навигацию.
Во первых хотелось бы сортировку по имени
Во вторых сделать список избранных проетков, которые бы были первыми в списке

**Comment by AndreiMuvila** [comment]
Здравствуйте.

В данный момент сортировка проектов действительно недоступна.

Мы портируем nxs-chat-srv с C на Go, так как текущая реализация не слишком удобна для прикручивания новых фич. Поэтому добавление их откладывается до завершения этого процесса.

Функционал сортировки и избранного планируется в новой версии. 

Требуется ли какая либо дополнительная нформация?

**Comment by openncomp** [comment]
Не могли бы вы уточнить о каких сроках идет речь, хотя бы примерно?

**Comment by borisershov** [comment]
Приветствую! Если не случится ничего непредвиденного, то новую версию мы планируем опубликовать, примерно, в середине апреля

**Comment by titkovdmitry** [comment]
По поводу изначального запроса, было бы круто, если бы он просто брал избранные проекты в редмайне и вставлял в начало, и внутри этих 2х списков была бы сортировка по имени.

И ещё всё таки сделать кнопку выбора на кого назначить, возможно так, чтобы в конфиге прописывать показывать ее или нет.

**Comment by borisershov** [comment]
This repository is considered deprecated and will be archived. For the new version of this tool please go to [Nixys Support Bot](https://github.com/nixys/nxs-support-bot) project.
