### ISSUE TITLE
Добавить выбор трекера

### ISSUE THREAD

**Issue by olegmm** [nixys/nxs-chat-srv#43]
Здравствуйте. 
Спасибо за удобную реализацию бота. 

Пожелание. Возможно ли добавить выбор трекера при создании задачи ?

![изображение](https://user-images.githubusercontent.com/3460830/234971041-85ef6c34-8a80-477d-a149-1261c45567a5.png)

**Comment by olegmm** [comment]
принимаете ли вы сейчас в принципе пожелания к разработке ?

**Comment by AndreiMuvila** [comment]
Здравствуйте.

Мы переписали нашего бота на Go, сейчас ведем тестирование. В ближайшие пару недель планируем выпустить новую версию.
Благодаря новой структуре, бот будет гораздо удобнее для доработки и внедрения нового функционала. Так же решена проблема с переполнением переменной UserID, из-за которой некоторые недавно зарегистрированные пользователи не могли использовать бота.

Что касается предложенной вами доработки, она уже в бэклоге и будет выпущена, вероятнее всего, в ближайший месяц.

**Comment by olegmm** [comment]
Здравствуйте, очень  следим за вашими нововведениями, сроки корректируются ?

**Comment by borisershov** [comment]
> Здравствуйте, очень следим за вашими нововведениями, сроки корректируются ?

Здравствуйте! Разработка новой версии бота завершена и уже прошла наше внутреннее тестирование. Всё работает корректно. Сейчас мы готовим документацию для новой версии бота. Планируем всё опубликовать на этой неделе.

**Comment by borisershov** [comment]
This repository is considered deprecated and will be archived. For the new version of this tool please go to [Nixys Support Bot](https://github.com/nixys/nxs-support-bot) project.

**Comment by borisershov** [comment]
This repository is considered deprecated and will be archived. For the new version of this tool please go to [Nixys Support Bot](https://github.com/nixys/nxs-support-bot) project.
