### ISSUE TITLE
Ошибка при добавлении файла в задачу

### ISSUE THREAD

**Issue by yakhlakov** [nixys/nxs-chat-srv#5]
Добрый день.
Моя конфигурация:
Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.3.4-p301 (2017-03-30) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
...
  nxs_chat                       1.5
...
  redmine_dropbox_attachments    2.2.1
...

Плагин redmine_dropbox_attachment складывает все файлы в Drop Box.

При попытке прикрепить файла к задаче появляется сообщение об ошибке:
![image](https://user-images.githubusercontent.com/34373452/35635917-a3ecd980-06c0-11e8-9ce7-fb8901fd3574.png)

В логах:
```
[31.01.2018 16:47:54.990034]	(14)	DEBUG:		[queue-worker]: tlgrm file download: success
[31.01.2018 16:47:56.545257]	(14)	ERROR:		[queue-worker]: rdmn file upload error: wrong Redmine response code (file path: /var/spool/nxs-chat-srv/tlgrm/168634058/file_3.jpg, response code: 500, response body: "")
[31.01.2018 16:47:56.895946]	(14)	DEBUG:		[queue-worker]: tlgrm request: success
[31.01.2018 16:47:56.895981]	(14)	WARNING:	[queue-worker]: error in 'proc.queue-worker.tlgrm-update.handler_callback_sess_type_message' (user id: 168634058, error code: 2)
[31.01.2018 16:47:56.896115]	(14)	WARNING:	[queue-worker]: error in 'proc.queue-worker.tlgrm-update.handler_callback_exec' (user id: 168634058, error code: 2)
```

Понятное дело, что проблема в плагине redmine_dropbox_attachment. Можно ли ее как-то обойти?

Спасибо.

**Comment by borisershov** [comment]
Здравствуйте!

У меня пока два вопроса:
1. Если отключить в Redmine плагин redmine_dropbox_attachments, то будет ли загрузка файлов работать корректно?
2. Можете ли Вы привести лог Redmine с ошибкой при попытке загрузки?

**Comment by yakhlakov** [comment]
1. Отключил плагин, результат:
![image](https://user-images.githubusercontent.com/34373452/35642864-89cf8236-06d5-11e8-82e5-c4c86d115ed0.png)
2. Снова включаю плагин:
![image](https://user-images.githubusercontent.com/34373452/35643453-5cb04216-06d7-11e8-8f4b-3c9fefdce019.png)

Remine log:
```
Started POST "/uploads.json" for xx.xx.xx.xx at 2018-01-31 22:33:33 +0300
Processing by AttachmentsController#upload as JSON
  Current user: XX(id=43)
Completed 500 Internal Server Error in 16ms (ActiveRecord: 2.3ms)

NoMethodError (undefined method `split' for nil:NilClass):
  plugins/redmine_dropbox_attachments/lib/redmine_dropbox/attachments_controller_patch.rb:48:in `prepare_dropbox_redirect'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```
nxs-chat-srv log:

```
[31.01.2018 19:33:31.574971]	(13)	DEBUG:		[queue-worker]: tlgrm request: success
[31.01.2018 19:33:32.107607]	(13)	DEBUG:		[queue-worker]: tlgrm file download: success
[31.01.2018 19:33:33.713803]	(13)	ERROR:		[queue-worker]: rdmn file upload error: wrong Redmine response code (file path: /var/spool/nxs-chat-srv/tlgrm/168634058/file_7.png, response code: 500, response body: "")
[31.01.2018 19:33:33.961946]	(13)	DEBUG:		[queue-worker]: tlgrm request: success
[31.01.2018 19:33:33.961975]	(13)	WARNING:	[queue-worker]: error in 'proc.queue-worker.tlgrm-update.handler_message_sess_type_new_issue' (user id: 168634058, error code: 2)
[31.01.2018 19:33:33.962111]	(13)	WARNING:	[queue-worker]: error in 'proc.queue-worker.tlgrm-update.handler_message_exec' (user id: 168634058, error code: 2)
```

Вот часть кода, на которой происходит ошибка:
```
          # Since we uploads occur prior to an actual record being created,
          # the context needs to be parsed from the url.
          #   ex: http://url/projects/project_id/..../action_id
-->    ref = request.env["HTTP_REFERER"].split("/")
          # We also only want the url parts that follow .../projects/ if possible.
          # If not, just use the standard split HTTP_REFERER
          ref = ref[ref.index("projects") + 1 .. -1] if ref.index("projects")
```

**Comment by borisershov** [comment]
Здравствуйте!

Проверьте, пожалуйста, будет ли создаваться задача и прикрепляться к ней файлы если производить загрузку curl'ом из консоли?
Вот пример того как это можно сделать: http://www.redmine.org/projects/redmine/wiki/Rest_api_with_curl#Attaching-files (раздел **Attaching-files**)

**Comment by borisershov** [comment]
Дополню...

Если при проверке curl'ом будет выдаваться ошибка - отключите, пожалуйста, плагин nxs_chat и повторите загрузку. Сохранится ли проблема?

**Comment by yakhlakov** [comment]
Что с включенным, что с выключенным плагином nxs_chat лог аналогичный:
```
Started POST "/uploads.xml" for XX.XX.XX.XX at 2018-02-01 12:54:21 +0300
Processing by AttachmentsController#upload as XML
  Current user: admin (id=1)
Completed 500 Internal Server Error in 97ms (ActiveRecord: 69.1ms)

NoMethodError (undefined method `split' for nil:NilClass):
  plugins/redmine_dropbox_attachments/lib/redmine_dropbox/attachments_controller_patch.rb:48:in `prepare_dropbox_redirect'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Когда отключаю плагин dropbox - все ок:

```
<?xml version="1.0" encoding="UTF-8"?><upload><id>18</id>
token>18.0ec48c151eac763ac732dd2b03e22d1279ea6447a9ea337ff17ade67d1597977</token>
/upload>sergey@sergey-ubuntu:/var/data/redmine$
```

**Comment by borisershov** [comment]
Тогда я не уверен, что мы сможем Вам помочь с этим вопросом. Посмотрим, конечно, в команде, но результат не гарантирую.

Попробуйте написать Bug request разработчикам плагина для Dropbox. Полагаю, что это общая проблема, когда после включения их плагина перестаёт работать функционал загрузки файлов через API Redmine и они должны обратить на это внимание.
Сообщите, пожалуйста, когда будут какие-то результаты.

**Comment by yakhlakov** [comment]
Если указать ключ --referer в curl все работает.
С его помощью, видимо, плагин понимает куда складывать файлы в dropbox. Из-за этого и ошибка.

**Comment by borisershov** [comment]
Скажите, пожалуйста, а какое значение этого ключа Вы указывали?

Если можно, приведите полную команду для curl (разумеется, без указания приватных данных).

**Comment by yakhlakov** [comment]
Полная команда:

```
curl --data-binary "@image.png" -H "Content-Type: application/octet-stream" -X POST --referer https://domain.com/issues/1  -u login:pass https://domain.com/uploads.xml
Ответ:
<?xml version="1.0" encoding="UTF-8"?><upload><id>24</id><token>24.d41d8cd98f00b204e9800998ecf8427e</token></upload>
```

**Comment by borisershov** [comment]
Да, тогда Вам надо обратиться к разработчикам плагина [redmine_dropbox_attachments](https://github.com/alexbevi/redmine_dropbox_attachments) с описанием данной проблемы.
Со своей стороны мы помочь вряд ли сможем, к сожалению.

**Comment by yakhlakov** [comment]
Ок, в любом случае спасибо.
Думаю можно закрывать задачу.

**Comment by borisershov** [comment]
Не за что, обращайтесь!
Если будет возможность - напишите потом чем дело кончилось, пожалуйста.
