### ISSUE TITLE
Сборка Ubuntu Server

### ISSUE THREAD

**Issue by esuslik** [nixys/nxs-chat-srv#6]
Планируется ли сборка серврной части на ubuntu server 16.04.3 LTS?

**Comment by borisershov** [comment]
Здравствуйте!

На текущий момент мы планируем делать сборку только под Debian и CentOS. Для остальных ОС отлично подходит вариант с применением Docker. Привожу ссылку на [соответствующий раздел документации](https://github.com/nixys/nxs-chat-srv#dockerfile).

Дайте, пожалуйста, знать, если у Вас есть ещё какие-либо вопросы.

**Comment by borisershov** [comment]
Полагаю, что задача больше не актуальна.
