### ISSUE TITLE
file attachment

### ISSUE THREAD

**Issue by denchru** [nixys/nxs-chat-srv#9]
Не прикрепляются файлы к задаче, хотя визуально все отправляется и задачи создаются (если новая), но без  прикрепленного файла. 

В тоже время через сам рэд все файлы прикрепляются корректно. 
интересное замечание - если прикреплять PNG файл, то в логе с ошибкой у него расширение jpg.

[29.03.2018 23:26:12.234158]    (14285) WARNING:        [queue-worker]: rdmn file upload warn: Redmine unprocessable entity, possible exceeds the maximum file size allowed (file path: /var/spool/nxs-chat-srv/tlgrm/455384214/file_29.zip, response code: 422, response body: "{"errors":["Расширение  запрещено"]}")
[29.03.2018 23:26:12.293226]    (14287) DEBUG:          

[rest-api]: received message from redmine (auth token: "XXX" (correct), post body: "{"action":"issue_edit","data":{"issue":{"id":64,"project":
{"id":27,"name":"Pre-sale","members":[{"id":24,"name":"XXXXXX","access":{"view_current_issue":true,"view_private_notes":true},"roles":[{"id":9,"name":"менеджер задач","permissions":
{"issues_visibility":"default","view_private_notes":true}},{"id":3,"name":"Менеджер проекта","permissions":{"issues_visibility":"all","view_private_notes":true}}]},{"id":18,"name":"XXXXXX","access":
{"view_current_issue":true,"view_private_notes":true},"roles":[{"id":3,"name":"Менеджер проекта","permissions":{"issues_visibility":"all","view_private_notes":true}},{"id":9,"name":"менеджер задач","permissions":
{"issues_visibility":"default","view_private_notes":true}}]}]},"tracker":{"id":9,"name":"Новые задачи"},"status":{"id":1,"name":"Новая"},"priority":{"id":2,"name":"Нормальный"},"author":
{"id":24,"name":"XXXXXX"},"subject":"файл","description":"","start_date":"2018-03-29","due_date":null,"done_ratio":0,"is_private":false,"estimated_hours":null,"spent_hours":0.0,"custom_fields":[],
"created_on":"2018-03-29 20:08:32 UTC","updated_on":"2018-03-29 20:26:12 UTC","closed_on":null,"attachments":[],"journals":[{"id":null,"user":{"id":24,"name":"XXXXXX"},"notes":"","private_notes":false,"created_on":null,"details":[]}],
"watchers":[]}}}

[29.03.2018 23:26:12.293430]    (14287) DEBUG:          [rest-api]: ra queue add: success
[29.03.2018 23:26:12.293467]    (14287) INFO:           connection accepted     193.124.202.xxx:41606   "POST /redmine?token=XXX"        200     52      "Ruby"

**Comment by denchru** [comment]
Если redmine запускать через WEBrick , то сообщения только о 

/var/lib/gems/2.3.0/gems/actionpack-4.2.10/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::VCF
/var/lib/gems/2.3.0/gems/actionpack-4.2.10/lib/action_dispatch/http/mime_type.rb:163: warning: 






=> Booting WEBrick
=> Rails 4.2.10 application starting in production on http://xxxx:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
/var/lib/gems/2.3.0/gems/actionpack-4.2.10/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::VCF
/var/lib/gems/2.3.0/gems/actionpack-4.2.10/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of VCF was here
[2018-03-30 02:56:53] INFO  WEBrick 1.3.1
[2018-03-30 02:56:53] INFO  ruby 2.3.3 (2016-11-21) [x86_64-linux-gnu]
[2018-03-30 02:56:53] INFO  WEBrick::HTTPServer#start: pid=18093 port=3000

**Comment by borisershov** [comment]
Покажите, пожалуйста логи Redmine в момент проблемы с загрузкой файлов.

И ещё попробуйте загрузить файла в Redmine напрямую через API:
`curl -v -k -X POST -H "X-Redmine-API-Key: YOUR_REDMINE_API_KEY" -H  "Content-Type: application/octet-stream" --data @PATH_TO_FILE "https://YOUR_REDMINE_HOST/uploads.json"`
Сделайте для файлов с разными расширениями и покажите вывод, пожалуйста.

**Comment by denchru** [comment]
![image](https://user-images.githubusercontent.com/36408209/38195590-d46206e4-3686-11e8-9b6c-a20e9f06206a.png)


После очистки поля "допустимы расширения", проблема исчезла. Видимо где-то допустил ошибку в формате/форматах.

**Comment by borisershov** [comment]
> После очистки поля "допустимы расширения", проблема исчезла. Видимо где-то допустил ошибку в формате/форматах.

Скажите, пожалуйста, а что у Вас в этом поле было записано?

**Comment by pauloriply** [comment]
> > После очистки поля "допустимы расширения", проблема исчезла. Видимо где-то допустил ошибку в формате/форматах.
> 
> Скажите, пожалуйста, а что у Вас в этом поле было записано?

аналогичная проблема.
поле Допустимые расширения : txt,jpg,jpeg,png,bmp,rar,zip,pdf,doc,docx,pages,xls,xlsx,mov,xml,mp3
